// Code generated by goyacc -o parser_gen.go query.y. DO NOT EDIT.

//line query.y:2
package query

import __yyfmt__ "fmt"

//line query.y:2

import (
	"fmt"
	"github.com/google/uuid"
	"time"
)

const dateFormat = "2006/01/02 15:04:05"

//line query.y:14
type yySymType struct {
	yys                 int
	SelectQuery         SelectQuery
	CompoundSelectQuery CompoundSelectQuery
	LogicalOperator     LogicalOperator
	EqualityOperator    EqualityOperator
	String              string
	Strings             []string
	GroupQuery          GroupQuery
	GroupSelector       []string
	GroupToken          GroupToken
	GroupTokens         []GroupToken
	Number              int
	Query               Query
}

const STRING = 57346
const IDENTIFIER = 57347
const NUMBER = 57348
const EQUALS = 57349
const NOTEQUALS = 57350
const AND = 57351
const OR = 57352
const HASH = 57353
const BANG = 57354
const COMMA = 57355
const LPAREN = 57356
const RPAREN = 57357
const SESSION_ID = 57358
const ID = 57359
const NAME = 57360
const CLASSNAME = 57361
const TESTSUITE = 57362
const FILE = 57363
const STATUS = 57364
const GROUP_BY = 57365
const GROUP = 57366
const OFFSET = 57367
const LIMIT = 57368
const START_DATE = 57369
const END_DATE = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"IDENTIFIER",
	"NUMBER",
	"EQUALS",
	"NOTEQUALS",
	"AND",
	"OR",
	"HASH",
	"BANG",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"SESSION_ID",
	"ID",
	"NAME",
	"CLASSNAME",
	"TESTSUITE",
	"FILE",
	"STATUS",
	"GROUP_BY",
	"GROUP",
	"OFFSET",
	"LIMIT",
	"START_DATE",
	"END_DATE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line query.y:358

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 74

var yyAct = [...]int8{
	62, 21, 38, 39, 32, 33, 34, 35, 65, 54,
	4, 24, 25, 26, 27, 28, 29, 15, 16, 31,
	19, 20, 8, 9, 10, 11, 12, 13, 14, 40,
	64, 73, 48, 72, 67, 63, 66, 22, 23, 55,
	53, 52, 51, 50, 58, 57, 74, 70, 68, 60,
	59, 56, 49, 47, 46, 45, 44, 43, 42, 41,
	30, 17, 2, 1, 69, 61, 37, 36, 71, 18,
	3, 7, 6, 5,
}

var yyPact = [...]int16{
	6, -1000, -1000, 11, -1000, -1000, -1000, -1000, 30, 30,
	30, 30, 30, 30, 30, 56, 8, -21, 6, -1000,
	-1000, 55, -1000, -1000, 54, 53, 52, 51, 50, 49,
	30, 48, 36, 35, 34, 33, -1000, -1000, -5, 32,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 47, -1000,
	39, 38, 46, 45, 19, -6, -1000, -1000, -1000, -1000,
	-1000, 21, -1000, -1000, 44, 43, -1000, 19, -1000, 18,
	-1000, -1000, -1000, 42, -1000,
}

var yyPgo = [...]int8{
	0, 10, 73, 72, 71, 70, 69, 1, 67, 66,
	0, 65, 64, 63, 62, 61,
}

var yyR1 = [...]int8{
	0, 13, 14, 14, 15, 15, 15, 15, 15, 15,
	15, 5, 5, 6, 6, 1, 1, 1, 2, 2,
	2, 2, 2, 2, 2, 3, 3, 3, 4, 7,
	7, 8, 9, 11, 11, 10, 10, 12, 12,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 0, 4, 4, 4, 4, 2,
	2, 1, 3, 1, 1, 1, 1, 1, 3, 3,
	3, 3, 3, 3, 3, 4, 3, 2, 3, 1,
	1, 4, 5, 1, 3, 1, 2, 1, 3,
}

var yyChk = [...]int16{
	-1000, -13, -14, -5, -1, -2, -3, -4, 16, 17,
	18, 19, 20, 21, 22, 11, 12, -15, -6, 9,
	10, -7, 7, 8, -7, -7, -7, -7, -7, -7,
	4, 11, 25, 26, 27, 28, -8, -9, 23, 24,
	-1, 4, 4, 4, 4, 4, 4, 4, -7, 4,
	7, 7, 7, 7, 14, 7, 4, 6, 6, 4,
	4, -11, -10, 16, 11, 14, 15, 13, 4, -12,
	4, -10, 15, 13, 4,
}

var yyDef = [...]int8{
	2, -2, 4, 3, 11, 15, 16, 17, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 1, 0, 13,
	14, 0, 29, 30, 0, 0, 0, 0, 0, 0,
	27, 0, 0, 0, 0, 0, 9, 10, 0, 0,
	12, 18, 19, 20, 21, 22, 23, 24, 26, 28,
	0, 0, 0, 0, 0, 0, 25, 5, 6, 7,
	8, 0, 33, 35, 0, 0, 31, 0, 36, 0,
	37, 34, 32, 0, 38,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:51
		{
			yyVAL.Query = yyDollar[1].Query
			if yyDollar[2].Query.GroupQuery != nil {
				yyVAL.Query.GroupQuery = yyDollar[2].Query.GroupQuery
			}
			if yyDollar[2].Query.GroupSelector != nil {
				if yyDollar[2].Query.GroupQuery == nil {
					yylex.Error("group selector requires group_by clause")
					return 1
				}
				yyVAL.Query.GroupSelector = yyDollar[2].Query.GroupSelector
			}
			if yyDollar[2].Query.Offset != 0 {
				yyVAL.Query.Offset = yyDollar[2].Query.Offset
			}
			if yyDollar[2].Query.Limit != 0 {
				yyVAL.Query.Limit = yyDollar[2].Query.Limit
			}
			if yyDollar[2].Query.StartDate != nil {
				yyVAL.Query.StartDate = yyDollar[2].Query.StartDate
			}
			if yyDollar[2].Query.EndDate != nil {
				yyVAL.Query.EndDate = yyDollar[2].Query.EndDate
			}
			yylex.(*queryLexer).result = yyVAL.Query
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line query.y:81
		{
			yyVAL.Query = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:89
		{
			yyVAL.Query = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
			}
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line query.y:98
		{
			yyVAL.Query = Query{}
		}
	case 5:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:102
		{
			yyVAL.Query = yyDollar[1].Query
			yyVAL.Query.Offset = yyDollar[4].Number
		}
	case 6:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:107
		{
			yyVAL.Query = yyDollar[1].Query
			yyVAL.Query.Limit = yyDollar[4].Number
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:112
		{
			startDate, err := time.Parse(dateFormat, yyDollar[4].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid start_date format (expected YYYY/MM/DD HH:MM:SS): %s", yyDollar[4].String))
				return 1
			}
			yyVAL.Query = yyDollar[1].Query
			yyVAL.Query.StartDate = &startDate
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:122
		{
			endDate, err := time.Parse(dateFormat, yyDollar[4].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid end_date format (expected YYYY/MM/DD HH:MM:SS): %s", yyDollar[4].String))
				return 1
			}
			yyVAL.Query = yyDollar[1].Query
			yyVAL.Query.EndDate = &endDate
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:132
		{
			yyVAL.Query = yyDollar[1].Query
			gq := yyDollar[2].GroupQuery
			yyVAL.Query.GroupQuery = &gq
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:138
		{
			yyVAL.Query = yyDollar[1].Query
			yyVAL.Query.GroupSelector = yyDollar[2].GroupSelector
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:146
		{
			yyVAL.CompoundSelectQuery = CompoundSelectQuery{
				Parts: []CompoundSelectQueryPart{
					{Operator: OpAnd, Query: yyDollar[1].SelectQuery},
				},
			}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:154
		{
			yyVAL.CompoundSelectQuery = yyDollar[1].CompoundSelectQuery
			yyVAL.CompoundSelectQuery.Parts = append(yyVAL.CompoundSelectQuery.Parts, CompoundSelectQueryPart{
				Operator: yyDollar[2].LogicalOperator,
				Query:    yyDollar[3].SelectQuery,
			})
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:165
		{
			yyVAL.LogicalOperator = OpAnd
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:169
		{
			yyVAL.LogicalOperator = OpOr
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:176
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:180
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:184
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:191
		{
			sessionId, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid session_id (expected UUID): %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = SessionSelectQuery{
				SessionId: sessionId,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:203
		{
			id, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid id (expected UUID): %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = IdSelectQuery{
				Id:       id,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:215
		{
			yyVAL.SelectQuery = NameSelectQuery{
				Name:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:222
		{
			yyVAL.SelectQuery = ClassnameSelectQuery{
				Classname: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:229
		{
			yyVAL.SelectQuery = TestsuiteSelectQuery{
				Testsuite: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:236
		{
			yyVAL.SelectQuery = FileSelectQuery{
				File:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:243
		{
			validStatuses := []TestcaseStatus{StatusPass, StatusFail, StatusError, StatusSkip}
			var status TestcaseStatus
			isValid := false
			for _, s := range validStatuses {
				if string(s) == yyDollar[3].String {
					status = s
					isValid = true
					break
				}
			}
			if !isValid {
				yylex.Error(fmt.Sprintf("invalid status: %s (expected: pass, fail, error, skip)", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = StatusSelectQuery{
				Status:   status,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:267
		{
			yyVAL.SelectQuery = TagValueSelectQuery{
				Tag:      yyDollar[2].String,
				Value:    yyDollar[4].String,
				Operator: yyDollar[3].EqualityOperator,
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:275
		{
			yylex.Error(fmt.Sprintf("expected value after equality operator for tag %s", yyDollar[2].String))
			return 1
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:280
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[2].String,
				Operator: OpEq,
			}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:290
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[3].String,
				Operator: OpNEq,
			}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:300
		{
			yyVAL.EqualityOperator = OpEq
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:304
		{
			yyVAL.EqualityOperator = OpNEq
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:311
		{
			yyVAL.GroupQuery = GroupQuery{
				Tokens: yyDollar[3].GroupTokens,
			}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:320
		{
			yyVAL.GroupSelector = yyDollar[4].Strings
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:327
		{
			yyVAL.GroupTokens = []GroupToken{yyDollar[1].GroupToken}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:331
		{
			yyVAL.GroupTokens = append(yyDollar[1].GroupTokens, yyDollar[3].GroupToken)
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:338
		{
			yyVAL.GroupToken = SessionGroupToken{}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:342
		{
			yyVAL.GroupToken = TagGroupToken{Tag: yyDollar[2].String}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:349
		{
			yyVAL.Strings = []string{yyDollar[1].String}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:353
		{
			yyVAL.Strings = append(yyDollar[1].Strings, yyDollar[3].String)
		}
	}
	goto yystack /* stack new state and value */
}
