version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "dotnet-sdk"
    directory: "/client-blazor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tests_e2e"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/migration"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/util/greener-admin-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
