version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "dotnet-sdk"
    directory: "/client-blazor/GreenerBlazor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/util/greener-admin-cli"
    schedule:
      interval: "weekly"
