// Code generated by goyacc -o parser_gen.go query.y. DO NOT EDIT.

//line query.y:2
package query

import __yyfmt__ "fmt"

//line query.y:2

import (
	"fmt"
	"github.com/google/uuid"
)

//line query.y:11
type yySymType struct {
	yys                 int
	SelectQuery         SelectQuery
	CompoundSelectQuery CompoundSelectQuery
	LogicalOperator     LogicalOperator
	EqualityOperator    EqualityOperator
	String              string
	Strings             []string
	GroupQuery          GroupQuery
	GroupSelector       []string
	GroupToken          GroupToken
	GroupTokens         []GroupToken
}

const STRING = 57346
const IDENTIFIER = 57347
const EQUALS = 57348
const NOTEQUALS = 57349
const AND = 57350
const OR = 57351
const HASH = 57352
const BANG = 57353
const COMMA = 57354
const LPAREN = 57355
const RPAREN = 57356
const SESSION_ID = 57357
const ID = 57358
const NAME = 57359
const CLASSNAME = 57360
const TESTSUITE = 57361
const FILE = 57362
const STATUS = 57363
const GROUP_BY = 57364
const GROUP = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"IDENTIFIER",
	"EQUALS",
	"NOTEQUALS",
	"AND",
	"OR",
	"HASH",
	"BANG",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"SESSION_ID",
	"ID",
	"NAME",
	"CLASSNAME",
	"TESTSUITE",
	"FILE",
	"STATUS",
	"GROUP_BY",
	"GROUP",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line query.y:306

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 74

var yyAct = [...]int8{
	41, 26, 21, 43, 53, 25, 22, 23, 42, 62,
	4, 61, 29, 30, 31, 32, 33, 34, 16, 17,
	5, 21, 36, 9, 10, 11, 12, 13, 14, 15,
	5, 38, 19, 16, 17, 39, 24, 51, 9, 10,
	11, 12, 13, 14, 15, 55, 58, 54, 27, 28,
	63, 37, 59, 57, 56, 52, 60, 50, 49, 48,
	47, 46, 45, 44, 35, 3, 40, 20, 18, 2,
	8, 7, 6, 1,
}

var yyPact = [...]int16{
	8, -1000, -2, -21, -1000, -8, -1000, -1000, -1000, 42,
	42, 42, 42, 42, 42, 42, 60, 12, -21, -1000,
	23, 29, -1000, -1000, -1000, -7, 59, -1000, -1000, 58,
	57, 56, 55, 54, 53, 42, 51, -1000, -1000, -9,
	33, -1000, -1000, 50, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 49, -1000, 48, -1000, -7, -1000, -1000, -3, -1000,
	-1000, -1000, 46, -1000,
}

var yyPgo = [...]int8{
	0, 73, 10, 72, 71, 70, 69, 67, 1, 65,
	32, 0, 66, 46,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 6, 6,
	7, 7, 2, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 4, 4, 5, 8, 8, 9, 12, 12,
	11, 11, 10, 13, 13,
}

var yyR2 = [...]int8{
	0, 0, 1, 1, 2, 2, 3, 2, 1, 3,
	1, 1, 1, 1, 1, 3, 3, 3, 3, 3,
	3, 3, 2, 4, 3, 1, 1, 4, 1, 3,
	1, 2, 5, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, -6, -9, -2, 22, -3, -4, -5, 15,
	16, 17, 18, 19, 20, 21, 10, 11, -9, -10,
	-7, 23, 8, 9, -10, 13, -8, 6, 7, -8,
	-8, -8, -8, -8, -8, 4, 10, -10, -2, 6,
	-12, -11, 15, 10, 4, 4, 4, 4, 4, 4,
	4, -8, 4, 13, 14, 12, 4, 4, -13, 4,
	-11, 14, 12, 4,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 8, 0, 12, 13, 14, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 5, 7,
	0, 0, 10, 11, 4, 0, 0, 25, 26, 0,
	0, 0, 0, 0, 0, 22, 0, 6, 9, 0,
	0, 28, 30, 0, 15, 16, 17, 18, 19, 20,
	21, 0, 24, 0, 27, 0, 31, 23, 0, 33,
	29, 32, 0, 34,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line query.y:43
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
			}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:51
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:57
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:66
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
			}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:76
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
			}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:83
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:91
		{
			yylex.Error("group specification requires group_by clause")
			return 1
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:99
		{
			yyVAL.CompoundSelectQuery = CompoundSelectQuery{
				Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: yyDollar[1].SelectQuery},
				},
			}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:107
		{

			yyDollar[1].CompoundSelectQuery.Parts = append(yyDollar[1].CompoundSelectQuery.Parts, CompoundSelectQueryPart{Operator: yyDollar[2].LogicalOperator, Query: yyDollar[3].SelectQuery})
			yyVAL.CompoundSelectQuery = yyDollar[1].CompoundSelectQuery
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:116
		{
			yyVAL.LogicalOperator = OpAnd
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:120
		{
			yyVAL.LogicalOperator = OpOr
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:127
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:131
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:135
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:142
		{
			sessionId, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid UUID: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = SessionSelectQuery{
				SessionId: sessionId,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:154
		{
			id, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid UUID: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = IdSelectQuery{
				Id:       id,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:166
		{
			yyVAL.SelectQuery = NameSelectQuery{
				Name:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:173
		{
			yyVAL.SelectQuery = ClassnameSelectQuery{
				Classname: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:180
		{
			yyVAL.SelectQuery = TestsuiteSelectQuery{
				Testsuite: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:187
		{
			yyVAL.SelectQuery = FileSelectQuery{
				File:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:194
		{
			validStatuses := []TestcaseStatus{StatusPass, StatusFail, StatusError, StatusSkip}
			var status TestcaseStatus
			isValid := false
			for _, s := range validStatuses {
				if string(s) == yyDollar[3].String {
					status = s
					isValid = true
					break
				}
			}
			if !isValid {
				yylex.Error(fmt.Sprintf("invalid status: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = StatusSelectQuery{
				Status:   status,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:218
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[2].String,
				Operator: OpEq,
			}
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:225
		{
			yyVAL.SelectQuery = TagValueSelectQuery{
				Tag:      yyDollar[2].String,
				Value:    yyDollar[4].String,
				Operator: yyDollar[3].EqualityOperator,
			}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:236
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[3].String,
				Operator: OpNEq,
			}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:246
		{
			yyVAL.EqualityOperator = OpEq
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:250
		{
			yyVAL.EqualityOperator = OpNEq
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:257
		{
			yyVAL.GroupQuery = GroupQuery{
				Tokens: yyDollar[3].GroupTokens,
			}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:266
		{
			yyVAL.GroupTokens = []GroupToken{yyDollar[1].GroupToken}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:270
		{
			yyVAL.GroupTokens = append(yyDollar[1].GroupTokens, yyDollar[3].GroupToken)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:277
		{
			yyVAL.GroupToken = SessionGroupToken{}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:281
		{
			yyVAL.GroupToken = TagGroupToken{
				Tag: yyDollar[2].String,
			}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:290
		{
			yyVAL.GroupSelector = yyDollar[4].Strings
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:297
		{
			yyVAL.Strings = []string{yyDollar[1].String}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:301
		{
			yyVAL.Strings = append(yyDollar[1].Strings, yyDollar[3].String)
		}
	}
	goto yystack /* stack new state and value */
}
