// Code generated by goyacc -o parser_gen.go query.y. DO NOT EDIT.

//line query.y:2
package query

import __yyfmt__ "fmt"

//line query.y:2

import (
	"fmt"
	"github.com/google/uuid"
)

//line query.y:11
type yySymType struct {
	yys                 int
	SelectQuery         SelectQuery
	CompoundSelectQuery CompoundSelectQuery
	LogicalOperator     LogicalOperator
	EqualityOperator    EqualityOperator
	String              string
	Strings             []string
	GroupQuery          GroupQuery
	GroupSelector       []string
	GroupToken          GroupToken
	GroupTokens         []GroupToken
	Number              int
}

const STRING = 57346
const IDENTIFIER = 57347
const NUMBER = 57348
const EQUALS = 57349
const NOTEQUALS = 57350
const AND = 57351
const OR = 57352
const HASH = 57353
const BANG = 57354
const COMMA = 57355
const LPAREN = 57356
const RPAREN = 57357
const SESSION_ID = 57358
const ID = 57359
const NAME = 57360
const CLASSNAME = 57361
const TESTSUITE = 57362
const FILE = 57363
const STATUS = 57364
const GROUP_BY = 57365
const GROUP = 57366
const OFFSET = 57367
const LIMIT = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"IDENTIFIER",
	"NUMBER",
	"EQUALS",
	"NOTEQUALS",
	"AND",
	"OR",
	"HASH",
	"BANG",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"SESSION_ID",
	"ID",
	"NAME",
	"CLASSNAME",
	"TESTSUITE",
	"FILE",
	"STATUS",
	"GROUP_BY",
	"GROUP",
	"OFFSET",
	"LIMIT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line query.y:536

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 147

var yyAct = [...]uint8{
	59, 34, 18, 19, 27, 49, 50, 11, 12, 13,
	14, 15, 16, 17, 37, 38, 39, 40, 41, 42,
	18, 19, 28, 29, 6, 11, 12, 13, 14, 15,
	16, 17, 7, 121, 2, 3, 7, 27, 22, 23,
	27, 30, 31, 77, 78, 69, 56, 57, 115, 107,
	98, 52, 90, 71, 25, 122, 116, 108, 99, 91,
	32, 72, 61, 112, 131, 111, 85, 60, 84, 79,
	33, 44, 35, 36, 130, 127, 126, 120, 119, 51,
	114, 113, 106, 105, 95, 94, 102, 89, 88, 83,
	82, 76, 75, 55, 54, 53, 48, 47, 21, 20,
	135, 134, 133, 132, 129, 128, 125, 124, 118, 117,
	110, 109, 104, 103, 101, 100, 93, 92, 81, 80,
	74, 73, 46, 45, 5, 123, 97, 87, 86, 24,
	70, 68, 67, 66, 65, 64, 63, 62, 43, 96,
	58, 26, 4, 10, 9, 8, 1,
}

var yyPact = [...]int16{
	9, -1000, 92, 91, 13, 16, -1000, 56, -1000, -1000,
	-1000, 65, 65, 65, 65, 65, 65, 65, 134, 60,
	117, 116, 90, 89, -20, -1000, -9, 88, -1000, -1000,
	87, 86, 21, 51, 133, -1000, -1000, 132, 131, 130,
	129, 128, 127, 65, 126, 27, 36, 115, 114, 85,
	84, 18, -1000, 55, 113, 112, 83, 82, 53, -1000,
	-1000, 124, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 123,
	-1000, 81, 80, 26, 34, 111, 110, 78, 77, 122,
	24, 33, 109, 108, -1000, 51, -1000, -1000, 107, 106,
	76, 75, 23, 32, 105, 104, 50, -1000, 74, 73,
	22, 31, -1000, -1000, -1000, 103, 102, 71, 70, 7,
	30, -1000, 121, 101, 100, 69, 68, -1000, -1000, 99,
	98, 67, 57, -1000, -1000, -1000, 97, 96, -1000, -1000,
	95, 94, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 146, 24, 145, 144, 143, 142, 141, 1, 124,
	54, 0, 140, 139,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 6, 6, 7, 7, 2, 2, 2, 3,
	3, 3, 3, 3, 3, 3, 4, 4, 5, 8,
	8, 9, 12, 12, 11, 11, 10, 13, 13,
}

var yyR2 = [...]int8{
	0, 0, 3, 3, 6, 6, 1, 4, 4, 7,
	7, 1, 4, 4, 7, 7, 2, 5, 5, 8,
	8, 2, 5, 5, 8, 8, 3, 6, 6, 9,
	9, 2, 1, 3, 1, 1, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 2, 4, 3, 1,
	1, 4, 1, 3, 1, 2, 5, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, 25, 26, -6, -9, -2, 23, -3, -4,
	-5, 16, 17, 18, 19, 20, 21, 22, 11, 12,
	7, 7, 25, 26, -9, -10, -7, 24, 9, 10,
	25, 26, -10, 14, -8, 7, 8, -8, -8, -8,
	-8, -8, -8, 4, 11, 6, 6, 7, 7, 25,
	26, -10, -2, 7, 7, 7, 25, 26, -12, -11,
	16, 11, 4, 4, 4, 4, 4, 4, 4, -8,
	4, 26, 25, 6, 6, 7, 7, 25, 26, 14,
	6, 6, 7, 7, 15, 13, 4, 4, 7, 7,
	26, 25, 6, 6, 7, 7, -13, 4, 26, 25,
	6, 6, -11, 6, 6, 7, 7, 26, 25, 6,
	6, 15, 13, 7, 7, 26, 25, 6, 6, 7,
	7, 26, 25, 4, 6, 6, 7, 7, 6, 6,
	7, 7, 6, 6, 6, 6,
}

var yyDef = [...]int8{
	1, -2, 0, 0, 6, 11, 32, 0, 36, 37,
	38, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 21, 31, 0, 0, 34, 35,
	0, 0, 16, 0, 0, 49, 50, 0, 0, 0,
	0, 0, 0, 46, 0, 2, 3, 0, 0, 0,
	0, 26, 33, 0, 0, 0, 0, 0, 0, 52,
	54, 0, 39, 40, 41, 42, 43, 44, 45, 0,
	48, 0, 0, 7, 8, 0, 0, 0, 0, 0,
	12, 13, 0, 0, 51, 0, 55, 47, 0, 0,
	0, 0, 22, 23, 0, 0, 0, 57, 0, 0,
	17, 18, 53, 4, 5, 0, 0, 0, 0, 27,
	28, 56, 0, 0, 0, 0, 0, 9, 10, 0,
	0, 0, 0, 58, 14, 15, 0, 0, 24, 25,
	0, 0, 19, 20, 29, 30,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line query.y:45
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
			}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:53
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				Offset: yyDollar[3].Number,
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:62
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				Limit: yyDollar[3].Number,
			}
		}
	case 4:
		yyDollar = yyS[yypt-6 : yypt+1]
//line query.y:71
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				Offset: yyDollar[3].Number,
				Limit:  yyDollar[6].Number,
			}
		}
	case 5:
		yyDollar = yyS[yypt-6 : yypt+1]
//line query.y:81
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				Offset: yyDollar[6].Number,
				Limit:  yyDollar[3].Number,
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:91
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
			}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:97
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				Offset:      yyDollar[4].Number,
			}
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:104
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				Limit:       yyDollar[4].Number,
			}
		}
	case 9:
		yyDollar = yyS[yypt-7 : yypt+1]
//line query.y:111
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				Offset:      yyDollar[4].Number,
				Limit:       yyDollar[7].Number,
			}
		}
	case 10:
		yyDollar = yyS[yypt-7 : yypt+1]
//line query.y:119
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				Offset:      yyDollar[7].Number,
				Limit:       yyDollar[4].Number,
			}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:127
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
			}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:136
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
				Offset:     yyDollar[4].Number,
			}
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:146
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
				Limit:      yyDollar[4].Number,
			}
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line query.y:156
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
				Offset:     yyDollar[4].Number,
				Limit:      yyDollar[7].Number,
			}
		}
	case 15:
		yyDollar = yyS[yypt-7 : yypt+1]
//line query.y:167
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery: &yyDollar[1].GroupQuery,
				Offset:     yyDollar[7].Number,
				Limit:      yyDollar[4].Number,
			}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:178
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
			}
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:188
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
				Offset:        yyDollar[5].Number,
			}
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:199
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
				Limit:         yyDollar[5].Number,
			}
		}
	case 19:
		yyDollar = yyS[yypt-8 : yypt+1]
//line query.y:210
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
				Offset:        yyDollar[5].Number,
				Limit:         yyDollar[8].Number,
			}
		}
	case 20:
		yyDollar = yyS[yypt-8 : yypt+1]
//line query.y:222
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: CompoundSelectQuery{Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: EmptySelectQuery{}},
				}},
				GroupQuery:    &yyDollar[1].GroupQuery,
				GroupSelector: yyDollar[2].GroupSelector,
				Offset:        yyDollar[8].Number,
				Limit:         yyDollar[5].Number,
			}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:234
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
			}
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:241
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
				Offset:      yyDollar[5].Number,
			}
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:249
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
				Limit:       yyDollar[5].Number,
			}
		}
	case 24:
		yyDollar = yyS[yypt-8 : yypt+1]
//line query.y:257
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
				Offset:      yyDollar[5].Number,
				Limit:       yyDollar[8].Number,
			}
		}
	case 25:
		yyDollar = yyS[yypt-8 : yypt+1]
//line query.y:266
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery: yyDollar[1].CompoundSelectQuery,
				GroupQuery:  &yyDollar[2].GroupQuery,
				Offset:      yyDollar[8].Number,
				Limit:       yyDollar[5].Number,
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:275
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
			}
		}
	case 27:
		yyDollar = yyS[yypt-6 : yypt+1]
//line query.y:283
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
				Offset:        yyDollar[6].Number,
			}
		}
	case 28:
		yyDollar = yyS[yypt-6 : yypt+1]
//line query.y:292
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
				Limit:         yyDollar[6].Number,
			}
		}
	case 29:
		yyDollar = yyS[yypt-9 : yypt+1]
//line query.y:301
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
				Offset:        yyDollar[6].Number,
				Limit:         yyDollar[9].Number,
			}
		}
	case 30:
		yyDollar = yyS[yypt-9 : yypt+1]
//line query.y:311
		{
			yylex.(*queryLexer).result = Query{
				SelectQuery:   yyDollar[1].CompoundSelectQuery,
				GroupQuery:    &yyDollar[2].GroupQuery,
				GroupSelector: yyDollar[3].GroupSelector,
				Offset:        yyDollar[9].Number,
				Limit:         yyDollar[6].Number,
			}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:321
		{
			yylex.Error("group specification requires group_by clause")
			return 1
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:329
		{
			yyVAL.CompoundSelectQuery = CompoundSelectQuery{
				Parts: []CompoundSelectQueryPart{
					CompoundSelectQueryPart{Operator: OpAnd, Query: yyDollar[1].SelectQuery},
				},
			}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:337
		{

			yyDollar[1].CompoundSelectQuery.Parts = append(yyDollar[1].CompoundSelectQuery.Parts, CompoundSelectQueryPart{Operator: yyDollar[2].LogicalOperator, Query: yyDollar[3].SelectQuery})
			yyVAL.CompoundSelectQuery = yyDollar[1].CompoundSelectQuery
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:346
		{
			yyVAL.LogicalOperator = OpAnd
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:350
		{
			yyVAL.LogicalOperator = OpOr
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:357
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:361
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:365
		{
			yyVAL.SelectQuery = yyDollar[1].SelectQuery
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:372
		{
			sessionId, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid UUID: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = SessionSelectQuery{
				SessionId: sessionId,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:384
		{
			id, err := uuid.Parse(yyDollar[3].String)
			if err != nil {
				yylex.Error(fmt.Sprintf("invalid UUID: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = IdSelectQuery{
				Id:       id,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:396
		{
			yyVAL.SelectQuery = NameSelectQuery{
				Name:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:403
		{
			yyVAL.SelectQuery = ClassnameSelectQuery{
				Classname: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:410
		{
			yyVAL.SelectQuery = TestsuiteSelectQuery{
				Testsuite: yyDollar[3].String,
				Operator:  yyDollar[2].EqualityOperator,
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:417
		{
			yyVAL.SelectQuery = FileSelectQuery{
				File:     yyDollar[3].String,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:424
		{
			validStatuses := []TestcaseStatus{StatusPass, StatusFail, StatusError, StatusSkip}
			var status TestcaseStatus
			isValid := false
			for _, s := range validStatuses {
				if string(s) == yyDollar[3].String {
					status = s
					isValid = true
					break
				}
			}
			if !isValid {
				yylex.Error(fmt.Sprintf("invalid status: %s", yyDollar[3].String))
				return 1
			}
			yyVAL.SelectQuery = StatusSelectQuery{
				Status:   status,
				Operator: yyDollar[2].EqualityOperator,
			}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:448
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[2].String,
				Operator: OpEq,
			}
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:455
		{
			yyVAL.SelectQuery = TagValueSelectQuery{
				Tag:      yyDollar[2].String,
				Value:    yyDollar[4].String,
				Operator: yyDollar[3].EqualityOperator,
			}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:466
		{
			yyVAL.SelectQuery = TagSelectQuery{
				Tag:      yyDollar[3].String,
				Operator: OpNEq,
			}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:476
		{
			yyVAL.EqualityOperator = OpEq
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:480
		{
			yyVAL.EqualityOperator = OpNEq
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line query.y:487
		{
			yyVAL.GroupQuery = GroupQuery{
				Tokens: yyDollar[3].GroupTokens,
			}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:496
		{
			yyVAL.GroupTokens = []GroupToken{yyDollar[1].GroupToken}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:500
		{
			yyVAL.GroupTokens = append(yyDollar[1].GroupTokens, yyDollar[3].GroupToken)
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:507
		{
			yyVAL.GroupToken = SessionGroupToken{}
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line query.y:511
		{
			yyVAL.GroupToken = TagGroupToken{
				Tag: yyDollar[2].String,
			}
		}
	case 56:
		yyDollar = yyS[yypt-5 : yypt+1]
//line query.y:520
		{
			yyVAL.GroupSelector = yyDollar[4].Strings
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line query.y:527
		{
			yyVAL.Strings = []string{yyDollar[1].String}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line query.y:531
		{
			yyVAL.Strings = append(yyDollar[1].Strings, yyDollar[3].String)
		}
	}
	goto yystack /* stack new state and value */
}
