// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"

	"github.com/cephei8/greener/core/model/api"
	"github.com/cephei8/greener/core/model/db"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryServiceInterface creates a new instance of MockQueryServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryServiceInterface {
	mock := &MockQueryServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryServiceInterface is an autogenerated mock type for the QueryServiceInterface type
type MockQueryServiceInterface struct {
	mock.Mock
}

type MockQueryServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryServiceInterface) EXPECT() *MockQueryServiceInterface_Expecter {
	return &MockQueryServiceInterface_Expecter{mock: &_m.Mock}
}

// GetSession provides a mock function for the type MockQueryServiceInterface
func (_mock *MockQueryServiceInterface) GetSession(ctx context.Context, userID model_db.BinaryUUID, sessionID uuid.UUID) (*SessionDetail, error) {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *SessionDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, uuid.UUID) (*SessionDetail, error)); ok {
		return returnFunc(ctx, userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, uuid.UUID) *SessionDetail); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SessionDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model_db.BinaryUUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryServiceInterface_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockQueryServiceInterface_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model_db.BinaryUUID
//   - sessionID uuid.UUID
func (_e *MockQueryServiceInterface_Expecter) GetSession(ctx interface{}, userID interface{}, sessionID interface{}) *MockQueryServiceInterface_GetSession_Call {
	return &MockQueryServiceInterface_GetSession_Call{Call: _e.mock.On("GetSession", ctx, userID, sessionID)}
}

func (_c *MockQueryServiceInterface_GetSession_Call) Run(run func(ctx context.Context, userID model_db.BinaryUUID, sessionID uuid.UUID)) *MockQueryServiceInterface_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model_db.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(model_db.BinaryUUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryServiceInterface_GetSession_Call) Return(sessionDetail *SessionDetail, err error) *MockQueryServiceInterface_GetSession_Call {
	_c.Call.Return(sessionDetail, err)
	return _c
}

func (_c *MockQueryServiceInterface_GetSession_Call) RunAndReturn(run func(ctx context.Context, userID model_db.BinaryUUID, sessionID uuid.UUID) (*SessionDetail, error)) *MockQueryServiceInterface_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestcase provides a mock function for the type MockQueryServiceInterface
func (_mock *MockQueryServiceInterface) GetTestcase(ctx context.Context, userID model_db.BinaryUUID, testcaseID uuid.UUID) (*TestcaseDetail, error) {
	ret := _mock.Called(ctx, userID, testcaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestcase")
	}

	var r0 *TestcaseDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, uuid.UUID) (*TestcaseDetail, error)); ok {
		return returnFunc(ctx, userID, testcaseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, uuid.UUID) *TestcaseDetail); ok {
		r0 = returnFunc(ctx, userID, testcaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TestcaseDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model_db.BinaryUUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, testcaseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryServiceInterface_GetTestcase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestcase'
type MockQueryServiceInterface_GetTestcase_Call struct {
	*mock.Call
}

// GetTestcase is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model_db.BinaryUUID
//   - testcaseID uuid.UUID
func (_e *MockQueryServiceInterface_Expecter) GetTestcase(ctx interface{}, userID interface{}, testcaseID interface{}) *MockQueryServiceInterface_GetTestcase_Call {
	return &MockQueryServiceInterface_GetTestcase_Call{Call: _e.mock.On("GetTestcase", ctx, userID, testcaseID)}
}

func (_c *MockQueryServiceInterface_GetTestcase_Call) Run(run func(ctx context.Context, userID model_db.BinaryUUID, testcaseID uuid.UUID)) *MockQueryServiceInterface_GetTestcase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model_db.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(model_db.BinaryUUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryServiceInterface_GetTestcase_Call) Return(testcaseDetail *TestcaseDetail, err error) *MockQueryServiceInterface_GetTestcase_Call {
	_c.Call.Return(testcaseDetail, err)
	return _c
}

func (_c *MockQueryServiceInterface_GetTestcase_Call) RunAndReturn(run func(ctx context.Context, userID model_db.BinaryUUID, testcaseID uuid.UUID) (*TestcaseDetail, error)) *MockQueryServiceInterface_GetTestcase_Call {
	_c.Call.Return(run)
	return _c
}

// QueryGroups provides a mock function for the type MockQueryServiceInterface
func (_mock *MockQueryServiceInterface) QueryGroups(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Group], error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for QueryGroups")
	}

	var r0 *QueryResult[model_api.Group]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) (*QueryResult[model_api.Group], error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) *QueryResult[model_api.Group]); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*QueryResult[model_api.Group])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model_db.BinaryUUID, QueryParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryServiceInterface_QueryGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryGroups'
type MockQueryServiceInterface_QueryGroups_Call struct {
	*mock.Call
}

// QueryGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model_db.BinaryUUID
//   - params QueryParams
func (_e *MockQueryServiceInterface_Expecter) QueryGroups(ctx interface{}, userID interface{}, params interface{}) *MockQueryServiceInterface_QueryGroups_Call {
	return &MockQueryServiceInterface_QueryGroups_Call{Call: _e.mock.On("QueryGroups", ctx, userID, params)}
}

func (_c *MockQueryServiceInterface_QueryGroups_Call) Run(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams)) *MockQueryServiceInterface_QueryGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model_db.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(model_db.BinaryUUID)
		}
		var arg2 QueryParams
		if args[2] != nil {
			arg2 = args[2].(QueryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryServiceInterface_QueryGroups_Call) Return(queryResult *QueryResult[model_api.Group], err error) *MockQueryServiceInterface_QueryGroups_Call {
	_c.Call.Return(queryResult, err)
	return _c
}

func (_c *MockQueryServiceInterface_QueryGroups_Call) RunAndReturn(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Group], error)) *MockQueryServiceInterface_QueryGroups_Call {
	_c.Call.Return(run)
	return _c
}

// QuerySessions provides a mock function for the type MockQueryServiceInterface
func (_mock *MockQueryServiceInterface) QuerySessions(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Session], error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for QuerySessions")
	}

	var r0 *QueryResult[model_api.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) (*QueryResult[model_api.Session], error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) *QueryResult[model_api.Session]); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*QueryResult[model_api.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model_db.BinaryUUID, QueryParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryServiceInterface_QuerySessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuerySessions'
type MockQueryServiceInterface_QuerySessions_Call struct {
	*mock.Call
}

// QuerySessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model_db.BinaryUUID
//   - params QueryParams
func (_e *MockQueryServiceInterface_Expecter) QuerySessions(ctx interface{}, userID interface{}, params interface{}) *MockQueryServiceInterface_QuerySessions_Call {
	return &MockQueryServiceInterface_QuerySessions_Call{Call: _e.mock.On("QuerySessions", ctx, userID, params)}
}

func (_c *MockQueryServiceInterface_QuerySessions_Call) Run(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams)) *MockQueryServiceInterface_QuerySessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model_db.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(model_db.BinaryUUID)
		}
		var arg2 QueryParams
		if args[2] != nil {
			arg2 = args[2].(QueryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryServiceInterface_QuerySessions_Call) Return(queryResult *QueryResult[model_api.Session], err error) *MockQueryServiceInterface_QuerySessions_Call {
	_c.Call.Return(queryResult, err)
	return _c
}

func (_c *MockQueryServiceInterface_QuerySessions_Call) RunAndReturn(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Session], error)) *MockQueryServiceInterface_QuerySessions_Call {
	_c.Call.Return(run)
	return _c
}

// QueryTestcases provides a mock function for the type MockQueryServiceInterface
func (_mock *MockQueryServiceInterface) QueryTestcases(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Testcase], error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for QueryTestcases")
	}

	var r0 *QueryResult[model_api.Testcase]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) (*QueryResult[model_api.Testcase], error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model_db.BinaryUUID, QueryParams) *QueryResult[model_api.Testcase]); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*QueryResult[model_api.Testcase])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model_db.BinaryUUID, QueryParams) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryServiceInterface_QueryTestcases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryTestcases'
type MockQueryServiceInterface_QueryTestcases_Call struct {
	*mock.Call
}

// QueryTestcases is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model_db.BinaryUUID
//   - params QueryParams
func (_e *MockQueryServiceInterface_Expecter) QueryTestcases(ctx interface{}, userID interface{}, params interface{}) *MockQueryServiceInterface_QueryTestcases_Call {
	return &MockQueryServiceInterface_QueryTestcases_Call{Call: _e.mock.On("QueryTestcases", ctx, userID, params)}
}

func (_c *MockQueryServiceInterface_QueryTestcases_Call) Run(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams)) *MockQueryServiceInterface_QueryTestcases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model_db.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(model_db.BinaryUUID)
		}
		var arg2 QueryParams
		if args[2] != nil {
			arg2 = args[2].(QueryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryServiceInterface_QueryTestcases_Call) Return(queryResult *QueryResult[model_api.Testcase], err error) *MockQueryServiceInterface_QueryTestcases_Call {
	_c.Call.Return(queryResult, err)
	return _c
}

func (_c *MockQueryServiceInterface_QueryTestcases_Call) RunAndReturn(run func(ctx context.Context, userID model_db.BinaryUUID, params QueryParams) (*QueryResult[model_api.Testcase], error)) *MockQueryServiceInterface_QueryTestcases_Call {
	_c.Call.Return(run)
	return _c
}
