site_name: Greener
site_url: https://cephei8.github.io/greener
docs_dir: content
nav:
  - Greener: index.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
