name: CI

on:
  pull_request:

jobs:
  ci_build:
    name: (CI) Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: pipx install poetry

      - run: poetry install --with test
        working-directory: server

      - run: poetry run pytest -v .
        working-directory: server
