name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  release_create:
    name: (Release) Create release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: Docker Hub
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: pipx install poetry

      - run: poetry install --with test
        working-directory: server

      - run: poetry run pytest -v --postgres .
        working-directory: server

      - name: Prepare image tag
        run: |
          GREENER_IMAGE_TAG="${{ inputs.release_tag }}"
          GREENER_IMAGE_TAG="$(echo "$GREENER_IMAGE_TAG" | cut -c2-)"
          echo "GREENER_IMAGE_TAG=$GREENER_IMAGE_TAG" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: cephei8/greener:${{ env.GREENER_IMAGE_TAG }}

      - name: Create release
        run: |
          gh release create ${{ inputs.release_tag }}
        env:
          GH_TOKEN: ${{ github.token }}
